sudo: false
language: r
services:
  - postgresql
before_script:
  - bin/cpanm --notest Bio::SeqIO
  - psql -c 'create database shinyorthologs;' -U postgres
  - cd tests/data/
  - ./load.sh shinyorthologs
  - cd -
  - mv sample_config.json config.json
script:
  Rscript -e 'devtools::test()'

