sudo: false
language: r
cache: packages
bioc_required: true
services:
  - postgresql
before_script:
  - psql -c 'create database shinyorthologs;' -U postgres
  - cd tests/data/
  - psql -d shinyorthologs < create.sql
  - cd -
install:
  - ./install.sh
script:
  - Rscript -e 'shiny::runApp()'
  - Rscript -e 'devtools::test()'
