sudo: false
language: r
cache: packages
bioc_required: true
services:
  - postgresql
before_script:
  - psql -c 'create database shinyorthologs;' -U postgres
  - cd test/data/
  - psql -d shinyorthologs < create.sql
  - cd -
install:
  - ./install.sh
test:
  - Rscript -e 'shiny::runApp()'
