sudo: false
language: r
bioc_required: true
services:
  - postgresql
before_script:
  - psql -c 'create database shinyorthologs;' -U postgres
install:
  - ./install.sh
test:
  - Rscript -e 'shiny::runApp()'
