sudo: false
language: r
services:
  - postgresql
before_script:
  - bin/cpanm -l extlib Bio::SeqIO --notest
  - psql -c 'create database shinyorthologs;' -U postgres
  - cd tests/data/
  - ./load.sh shinyorthologs
  - cd -
  - mv sample_config.json config.json
test:
  Rscript -e 'devtools::test()'

