sudo: false
language: r
cache: packages
bioc_required: true
cache: packages
services:
  - postgresql
before_script:
  - psql -c 'create database shinyorthologs;' -U postgres
test:
  - Rscript -e 'shinyorthologs::shinyorthologs(db_name="shinyorthologs")'
