sudo: false
language: r
bioc_required: true
r_packages:
  - testthat
services:
  - postgresql
before_script:
  - psql -c 'create database shinyorthologs;' -U postgres
  - cd tests/data/
  - cpanm -l extlib Bio::SeqIO --notest
  - ./load.sh
  - cd -
  - mv sample_config.json config.json
install:
  - ./install.sh
script:
  - Rscript -e 'devtools::test()'
