CREATE EXTENSION tablefunc;
CREATE TABLE species (SPECIES_ID varchar(255) PRIMARY KEY, TRANSCRIPTOME_FASTA varchar(255), SPECIES_NAME varchar(255), EXPRESSION_FILE varchar(255), TAXONOMY_ID int, COMMON_NAME varchar(255));
CREATE TABLE genes (GENE_ID varchar(255) PRIMARY KEY, SPECIES_ID varchar(255) REFERENCES species, SYMBOL varchar(255));
CREATE TABLE orthodescriptions (ORTHOLOG_ID varchar(255) PRIMARY KEY, DESCRIPTION varchar(2024));
CREATE TABLE orthologs (ORTHOLOG_ID varchar(255) REFERENCES orthodescriptions, SPECIES_ID varchar(255) REFERENCES species, GENE_ID varchar(255) REFERENCES genes, EVIDENCE varchar(255));
CREATE TABLE transcripts (TRANSCRIPT_ID varchar(255), GENE_ID varchar(255));
COPY species FROM 'C:/Users/2010/Desktop/extdata/species.csv' CSV HEADER;
COPY genes FROM 'C:/Users/2010/Desktop/extdata/genes.csv' CSV HEADER;
COPY orthodescriptions FROM 'C:/Users/2010/Desktop/extdata/ortho_descriptions.csv' CSV HEADER DELIMITER E'\t';
COPY orthologs FROM 'C:/Users/2010/Desktop/extdata/orthologs.csv' CSV HEADER;
COPY transcripts FROM 'C:/Users/2010/Desktop/extdata/transcripts.csv' CSV HEADER;
