utils::globalVariables(
    c(
        "orthologUI",
        "orthologServer",
        "searchUI",
        "searchServer",
        "helpUI",
        "helpServer",
        "editUI",
        "editServer",
        "speciesUI",
        "speciesServer",
        "comparisonsUI",
        "comparisonsServer",
        "msaUI",
        "msaServer",
        "genepageUI",
        "genepageServer",
        "runShinyOrthologs",
        "runShinyOrthologsDev",
        "dbargs",
        "basedir",
        "expressionFiles",
        "fastaIndexes"
    )
)
